version: "3.9"

services:
  web:
    build: .
    container_name: cantina-web
    command: gunicorn cantinasf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always