# Generated by Django 5.1.8 on 2025-06-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantinaSF', '0004_transaction_delete_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cantinaSF.history'),
        ),
    ]
