# Generated by Django 5.1.8 on 2025-06-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantinaSF', '0005_alter_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], default='debito', max_length=10),
        ),
    ]
